### ISSUE TITLE
maybe update to 1.12

### ISSUE THREAD

**Issue by zabory** [salmjak/Pixelmon-3-Command-Blocks#1]
Uh so it would be great if you could update this to the 1.12.2 version of minecraft and current version of pixelmon. Please and thank you so much. (ps the new pixelmon is called pixelmon reforged)

**Comment by HSavageheart** [comment]
SAME it needed for my Modpack
cause the mod doesnt have the scoreboard for what i need

**Comment by salmjak** [comment]
It has been done
